version: "2"

run:
  timeout: 5m
  go: "1.25"

linters-settings:
  gocritic:
    enabled-tags:
    - performance
  gosec:
    excludes:
    - G108
  lll:
    line-length: 200

  misspell:
    locale: US

linters:
  disable-all: true
  enable:
  - errcheck
  - copyloopvar
  - forcetypeassert
  - gocritic
  - goconst
  - godot
  - gosec
  - govet
  - ineffassign
  - misspell
  - nilerr
  - revive # replacement for golint
  - staticcheck
  - unused
  - whitespace

formatters:
  enable:
  - gofmt
  - gofumpt
  - goimports

issues:
  exclude:
    - 'deprecated: This package is intended for older projects transitioning from OPA v0.x and will remain for the lifetime of OPA v1.x'
