resources:
- templates.gatekeeper.sh_constrainttemplates.yaml
- externaldata.gatekeeper.sh_providers.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: constrainttemplates.templates.gatekeeper.sh
    spec:
      preserveUnknownFields: false
